name: Secrets
on: workflow_dispatch
jobs:
  create-or-update-secret:
    name: Check Secrets
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: hmanzur/actions-set-secret@v2.0.0
        with:
          name: 'MY_SECRET_NAME'
          value: ${{ secrets.MY_SECRET_NAME_VALUE }}
          repository: ajaychinthapalli/github-actions-secrets
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
