name: Secrets

on: push

jobs:
  create-or-update-secret:
    name: Check Secrets
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: hmanzur/actions-set-secret@v2.0.0
        with:
          name: 'MY_SECRET_NAME'
          value: 'Lorem ipsun dolor simit'
          repository: hmanzur/actions-set-secret
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
